# Script to run all experements for tranfer learning cross scales with MIL
# make sure conda activate clam has been run so environment is activated! 

# declare -a models=("../CNNs/meta_pretrained/dino_rn50_checkpoint.pth" "..CNNs/FlockNet_1X/checkpoint0099.pth")
# Define models names

declare -a model_names=("imagenet_dino_baseline" "FlockNet1X" "FlockNet2X" "FlockNet2X_half" "random" "imagenet_supervised")
# declare -a model_names=("FlockNet2X" "FlockNet2X_half" "random" "imagenet_supervised" "FlockNet1X_NEW" "ImageNet_Large")

# label for the experements incase you need to re-run experiments.
length=${#model_names[@]}

for ((i = 0; i < length; i++)); 
    do
    model_name="${model_names[$i]}"

    experement_number="3"  
    # ===== Run all experements =====
    CUDA_VISIBLE_DEVICES=1 python main.py --lr 1e-3 --k 10 --exp_code task_1_tumor_vs_normal_CLAM_50 --bag_loss ce --inst_loss svm --task task_1_tumor_vs_normal --model_type clam_sb --log_data --data_root_dir . --embedding_size 1000 --data_dir /local_storage/FINAL_CLAM_FEATURES/20X/HunCRC/$model_name --exp_code HunCRC_$model_name"_"$experement_number --split_dir HunCRC_10_fold_100 --data_csv data_cleaning/dataset_csv/HunCRC_CRC_vs_clear.csv --early_stopping  --max_epochs 100 --results_dir ./results_clam_20X/HunCRC  &
    CUDA_VISIBLE_DEVICES=1 python main.py --lr 1e-3 --k 10 --exp_code task_1_tumor_vs_normal_CLAM_50 --bag_loss ce --inst_loss svm --task task_1_tumor_vs_normal --model_type clam_sb --log_data --data_root_dir . --embedding_size 1000 --data_dir /local_storage/FINAL_CLAM_FEATURES/20X/Yale/$model_name --exp_code Yale_$model_name"_"$experement_number --split_dir Yale_10_fold_100 --data_csv data_cleaning/dataset_csv/Yale_HER2_status.csv --early_stopping  --max_epochs 100 --results_dir ./results_clam_20X/Yale  &
    CUDA_VISIBLE_DEVICES=0 python main.py --lr 1e-3 --k 10 --exp_code task_1_tumor_vs_normal_CLAM_50 --bag_loss ce --inst_loss svm --task task_1_tumor_vs_normal --model_type clam_sb --log_data --data_root_dir . --embedding_size 1000 --data_dir /local_storage/FINAL_CLAM_FEATURES/20X/Ovarian/$model_name --exp_code Ovarian_$model_name"_"$experement_number --split_dir Ovarian_10_fold_100 --data_csv data_cleaning/dataset_csv/Ovarian_responce.csv --early_stopping  --max_epochs 100 --results_dir ./results_clam_20X/Ovarian & 
    CUDA_VISIBLE_DEVICES=0 python main.py --lr 1e-3 --k 10 --exp_code task_1_tumor_vs_normal_CLAM_50 --bag_loss ce --inst_loss svm --task task_1_tumor_vs_normal --model_type clam_sb --log_data --data_root_dir . --embedding_size 1000 --data_dir /local_storage/FINAL_CLAM_FEATURES/20X/Bracs/$model_name --exp_code Bracs_$model_name"_"$experement_number --split_dir Bracs_10_fold_100 --data_csv data_cleaning/dataset_csv/BRACS_malignancy.csv --max_epochs 100  --early_stopping   --results_dir ./results_clam_20X/Bracs & 
    CUDA_VISIBLE_DEVICES=2 python main.py --lr 1e-3 --k 10 --exp_code task_1_tumor_vs_normal_CLAM_50 --bag_loss ce --inst_loss svm --task task_1_tumor_vs_normal --model_type clam_sb --log_data --data_root_dir . --embedding_size 1000 --data_dir /local_storage/FINAL_CLAM_FEATURES/20X/DLBCL/$model_name --exp_code DLBCL_$model_name"_"$experement_number --split_dir DLBCL_10_fold_100 --data_csv data_cleaning/dataset_csv/DLBCL_6Year_PFS.csv --max_epochs 100  --early_stopping  --results_dir ./results_clam_20X/DLBCL & 
    CUDA_VISIBLE_DEVICES=2 python main.py --lr 1e-3 --k 10 --exp_code task_1_tumor_vs_normal_CLAM_50 --bag_loss ce --inst_loss svm --task task_1_tumor_vs_normal --model_type clam_sb --log_data --data_root_dir . --embedding_size 1000 --data_dir /local_storage/FINAL_CLAM_FEATURES/20X/PANDA/$model_name --exp_code PANDA_$model_name"_"$experement_number --split_dir PANDA_10_fold_100 --data_csv data_cleaning/dataset_csv/PANDA_final.csv --max_epochs 100  --early_stopping  --results_dir ./results_clam_20X/PANDA & 


    experement_number="4" 
    # ===== Run all experements =====
    CUDA_VISIBLE_DEVICES=1 python main.py --lr 1e-4 --k 10 --exp_code task_1_tumor_vs_normal_CLAM_50 --bag_loss ce --inst_loss svm --task task_1_tumor_vs_normal --model_type clam_sb --log_data --data_root_dir . --embedding_size 1000 --data_dir /local_storage/FINAL_CLAM_FEATURES/20X/HunCRC/$model_name --exp_code HunCRC_$model_name"_"$experement_number --split_dir HunCRC_10_fold_100 --data_csv data_cleaning/dataset_csv/HunCRC_CRC_vs_clear.csv --early_stopping  --max_epochs 100 --results_dir ./results_clam_20X/HunCRC  &
    CUDA_VISIBLE_DEVICES=1 python main.py --lr 1e-4 --k 10 --exp_code task_1_tumor_vs_normal_CLAM_50 --bag_loss ce --inst_loss svm --task task_1_tumor_vs_normal --model_type clam_sb --log_data --data_root_dir . --embedding_size 1000 --data_dir /local_storage/FINAL_CLAM_FEATURES/20X/Yale/$model_name --exp_code Yale_$model_name"_"$experement_number --split_dir Yale_10_fold_100 --data_csv data_cleaning/dataset_csv/Yale_HER2_status.csv --early_stopping  --max_epochs 100 --results_dir ./results_clam_20X/Yale  &
    CUDA_VISIBLE_DEVICES=1 python main.py --lr 1e-4 --k 10 --exp_code task_1_tumor_vs_normal_CLAM_50 --bag_loss ce --inst_loss svm --task task_1_tumor_vs_normal --model_type clam_sb --log_data --data_root_dir . --embedding_size 1000 --data_dir /local_storage/FINAL_CLAM_FEATURES/20X/Ovarian/$model_name --exp_code Ovarian_$model_name"_"$experement_number --split_dir Ovarian_10_fold_100 --data_csv data_cleaning/dataset_csv/Ovarian_responce.csv --early_stopping  --max_epochs 100 --results_dir ./results_clam_20X/Ovarian & 
    CUDA_VISIBLE_DEVICES=0 python main.py --lr 1e-4 --k 10 --exp_code task_1_tumor_vs_normal_CLAM_50 --bag_loss ce --inst_loss svm --task task_1_tumor_vs_normal --model_type clam_sb --log_data --data_root_dir . --embedding_size 1000 --data_dir /local_storage/FINAL_CLAM_FEATURES/20X/Bracs/$model_name --exp_code Bracs_$model_name"_"$experement_number --split_dir Bracs_10_fold_100 --data_csv data_cleaning/dataset_csv/BRACS_malignancy.csv --max_epochs 100  --early_stopping   --results_dir ./results_clam_20X/Bracs & 
    CUDA_VISIBLE_DEVICES=2 python main.py --lr 1e-4 --k 10 --exp_code task_1_tumor_vs_normal_CLAM_50 --bag_loss ce --inst_loss svm --task task_1_tumor_vs_normal --model_type clam_sb --log_data --data_root_dir . --embedding_size 1000 --data_dir /local_storage/FINAL_CLAM_FEATURES/20X/DLBCL/$model_name --exp_code DLBCL_$model_name"_"$experement_number --split_dir DLBCL_10_fold_100 --data_csv data_cleaning/dataset_csv/DLBCL_6Year_PFS.csv --max_epochs 100  --early_stopping  --results_dir ./results_clam_20X/DLBCL & 
    CUDA_VISIBLE_DEVICES=2 python main.py --lr 1e-4 --k 10 --exp_code task_1_tumor_vs_normal_CLAM_50 --bag_loss ce --inst_loss svm --task task_1_tumor_vs_normal --model_type clam_sb --log_data --data_root_dir . --embedding_size 1000 --data_dir /local_storage/FINAL_CLAM_FEATURES/20X/PANDA/$model_name --exp_code PANDA_$model_name"_"$experement_number --split_dir PANDA_10_fold_100 --data_csv data_cleaning/dataset_csv/PANDA_final.csv --max_epochs 100  --early_stopping  --results_dir ./results_clam_20X/PANDA & 

    experement_number="5" 
    # ===== Run all experements =====
    CUDA_VISIBLE_DEVICES=1 python main.py --lr 1e-5 --k 10 --exp_code task_1_tumor_vs_normal_CLAM_50 --bag_loss ce --inst_loss svm --task task_1_tumor_vs_normal --model_type clam_sb --log_data --data_root_dir . --embedding_size 1000 --data_dir /local_storage/FINAL_CLAM_FEATURES/20X/HunCRC/$model_name --exp_code HunCRC_$model_name"_"$experement_number --split_dir HunCRC_10_fold_100 --data_csv data_cleaning/dataset_csv/HunCRC_CRC_vs_clear.csv --early_stopping  --max_epochs 100 --results_dir ./results_clam_20X/HunCRC  &
    CUDA_VISIBLE_DEVICES=1 python main.py --lr 1e-5 --k 10 --exp_code task_1_tumor_vs_normal_CLAM_50 --bag_loss ce --inst_loss svm --task task_1_tumor_vs_normal --model_type clam_sb --log_data --data_root_dir . --embedding_size 1000 --data_dir /local_storage/FINAL_CLAM_FEATURES/20X/Yale/$model_name --exp_code Yale_$model_name"_"$experement_number --split_dir Yale_10_fold_100 --data_csv data_cleaning/dataset_csv/Yale_HER2_status.csv --early_stopping  --max_epochs 100 --results_dir ./results_clam_20X/Yale  &
    CUDA_VISIBLE_DEVICES=2 python main.py --lr 1e-5 --k 10 --exp_code task_1_tumor_vs_normal_CLAM_50 --bag_loss ce --inst_loss svm --task task_1_tumor_vs_normal --model_type clam_sb --log_data --data_root_dir . --embedding_size 1000 --data_dir /local_storage/FINAL_CLAM_FEATURES/20X/Ovarian/$model_name --exp_code Ovarian_$model_name"_"$experement_number --split_dir Ovarian_10_fold_100 --data_csv data_cleaning/dataset_csv/Ovarian_responce.csv --early_stopping  --max_epochs 100 --results_dir ./results_clam_20X/Ovarian & 
    CUDA_VISIBLE_DEVICES=0 python main.py --lr 1e-5 --k 10 --exp_code task_1_tumor_vs_normal_CLAM_50 --bag_loss ce --inst_loss svm --task task_1_tumor_vs_normal --model_type clam_sb --log_data --data_root_dir . --embedding_size 1000 --data_dir /local_storage/FINAL_CLAM_FEATURES/20X/Bracs/$model_name --exp_code Bracs_$model_name"_"$experement_number --split_dir Bracs_10_fold_100 --data_csv data_cleaning/dataset_csv/BRACS_malignancy.csv --max_epochs 100  --early_stopping   --results_dir ./results_clam_20X/Bracs & 
    CUDA_VISIBLE_DEVICES=2 python main.py --lr 1e-5 --k 10 --exp_code task_1_tumor_vs_normal_CLAM_50 --bag_loss ce --inst_loss svm --task task_1_tumor_vs_normal --model_type clam_sb --log_data --data_root_dir . --embedding_size 1000 --data_dir /local_storage/FINAL_CLAM_FEATURES/20X/DLBCL/$model_name --exp_code DLBCL_$model_name"_"$experement_number --split_dir DLBCL_10_fold_100 --data_csv data_cleaning/dataset_csv/DLBCL_6Year_PFS.csv --max_epochs 100  --early_stopping  --results_dir ./results_clam_20X/DLBCL & 
    CUDA_VISIBLE_DEVICES=2 python main.py --lr 1e-5 --k 10 --exp_code task_1_tumor_vs_normal_CLAM_50 --bag_loss ce --inst_loss svm --task task_1_tumor_vs_normal --model_type clam_sb --log_data --data_root_dir . --embedding_size 1000 --data_dir /local_storage/FINAL_CLAM_FEATURES/20X/PANDA/$model_name --exp_code PANDA_$model_name"_"$experement_number --split_dir PANDA_10_fold_100 --data_csv data_cleaning/dataset_csv/PANDA_final.csv --max_epochs 100  --early_stopping  --results_dir ./results_clam_20X/PANDA & 

    wait
done

